[package]
name = "banksystem-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27"
tui = "0.19"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
